// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © QuantCT

//@version=4
strategy("PMA Strategy",
         shorttitle="PMA", 
         overlay=true,
         pyramiding=0,     
         default_qty_type=strategy.percent_of_equity, 
         default_qty_value=100, 
         initial_capital=100,           
         commission_type=strategy.commission.percent, 
         commission_value=0.075)

ema1_period = input(title="EMA1 Period", defval=10)
ema2_period = input(title="EMA2 Period", defval=20)
ema3_period = input(title="EMA3 Period", defval=30)
show_bg = input(title="Show Background?", defval=true)

ema1 = ema(hlc3, ema1_period)
ema2 = ema(hlc3, ema2_period)
ema3 = ema(hlc3, ema3_period)

buy_condition = (rising(ema1, 1) and rising(ema2, 1) and rising(ema3, 1))
sell_condition = (not rising(ema1, 1) and not rising(ema2, 1) and not rising(ema3, 1))

strategy.entry("Buy", strategy.long, when=buy_condition)
strategy.close("Buy", when=sell_condition)

colors = 
 buy_condition ? #27D600 :
 sell_condition ? #E30202 :
 color.orange

ema1_plot = plot(ema1, color=colors)
ema2_plot = plot(ema2, color=colors)
ema3_plot = plot(ema3, color=colors)

fill(ema1_plot, ema3_plot, color=show_bg ? colors : na, transp=50)

